#CloudFormationTemplateVersion
#Description

AWSTemplateFormatVersion: '2010-09-09'
Description: 'CloudFormation Template for S3'
Resources: 
 S3Bucket:
  Type: AWS::S3::Bucket
  Properties:
   BucketName: shweta-s3-bucket-yaml